### ISSUE TITLE
Merge des 2 versions de lutim

### ISSUE THREAD

**Issue by maniackcrudelis** [maniackcrudelis/lutim_ynh#1]
J'ouvre une issue pour voir comment merger nos travaux respectif.
Si cela te convient.

**Comment by maniackcrudelis** [comment]
Bon, pour le moment, je suis confronté à des nouvelles erreurs avec carton, qui me sort soudainement des erreurs de dépendances sur d'autres modules. Il est d'humeur taquine aujourd'hui.

Mais je note déjà quelques différences:
- Tu récupères les sources depuis github, là ou j'ai choisi des sources locale (pour éviter des maj non gérées par le script)
- Tu utilises un user lutim dédié
Pour ce que j'ai vu rapidement, car je me prend la tête avec carton...

**Comment by matlink** [comment]
Je n'ai suivi que ce tuto : http://framacloud.org/cultiver-son-jardin/installation-de-lutim/ 
Il est peut-être plus sage d'embarquer les sources en effet, à voir.
As tu une adresse xmpp que ce soit plus simple pour discuter de cela ?

**Comment by maniackcrudelis** [comment]
Oui, maniack@crudelis.fr
Mais je suis pas très présent car j'ai malheureusement pas beaucoup de temps.
Je garderais toutefois mon client jabber actif quand je serais sur lutim.

Je veux bien que tu fasses un essai de mon package pour voir si tout les problèmes que je rencontre aujourd'hui sont à incomber à ma VM ou pas.

**Comment by matlink** [comment]
Le problème est que je n'ai pas très envie de supprimer mon install' sur mon serv de prod. Je vais tester sur mon rpi.

**Comment by maniackcrudelis** [comment]
En coup de vent, avec un VM à la bonne heure (ça va m'agacer ça!), le setup se passe bien. J'avais un guillemet simple mal placé dans le fichier de conf.
Il est intéressant d'ailleurs de savoir que le service ne démarre pas pour ce genre d'erreur. Mais sans log, car le fichier init.d filtre sa sortie.
Il faut faire sauter la redirection d'erreur dans la section start pour voir les problèmes de démarrage.

**Comment by matlink** [comment]
Oui, il peut être intéressant de mettre la sortie standard du service lutim dans un fichier de log (/var/log/lutim/lutim.conf) par exemple, afin d'aider le debuggage. Ainsi, lutim pourra être géré au niveau de l'interface web également (on pourra y consulter les logs, start/stop, enable/disable le service).

**Comment by maniackcrudelis** [comment]
J'avais envisagé de passer lutim en service dans l'interface ynh, mais j'avais mis l'idée de côté (par flemme sans doute, je ne me sert jamais de cette interface). Toutefois, il est vrai que Mme Michu se sert rarement de ssh, donc il serait bon de le passer par ynh. Et de rétablir un log par la même occasion. En revanche, j'ignore où on passe le log dans le fichier init.

**Comment by maniackcrudelis** [comment]
Je décortique un peu ton script pour voir les points à merger.

La vérif du port, https://github.com/matlink/lutim_ynh/blob/master/scripts/install#L12. 
Bon... j'allais dire qu'il fallait éviter pour ne pas ouvrir le port sur le firewall, mais en fait non, c'est encore une autre commande. Donc c'est plutôt une bonne idée!

https://github.com/matlink/lutim_ynh/blob/master/scripts/install#L33
C'est une bonne idée également de vérifier le dossier cible, je ne le fais jamais, mais c'est plutôt bon de vérifier.

https://github.com/matlink/lutim_ynh/blob/master/scripts/install#L69
Très judicieux, c'est à garder!

Par contre je suis surpris que tu n'es pas de problème avec les droits du service.
https://github.com/ldidry/lutim/issues/50
Pour ma part, je suis forcé de patcher le script init, sinon il créé ses fichiers en root et hypnotoad ne peux plus les lire!

https://github.com/matlink/lutim_ynh/blob/master/scripts/install#L92
C'est quoi? Je ne connais pas cette commande ynh.

https://github.com/matlink/lutim_ynh/blob/master/scripts/install#L95
Je créé une issue pour ça, c'est le point où je bloque pour le moment...

**Comment by maniackcrudelis** [comment]
Que dirais-tu d'un [kanboard](http://kanboard.net/) pour organiser le travail restant à faire?
Il y a un package pour ynh qui marche très bien.

(Dernier spam pour cette nuit, promis)

**Comment by matlink** [comment]
Salut !

- Kanboard je connais pas c'est une bonne idée pour organiser le travail. Je te laisse créer le truc et m'inviter.
- la vérif du port, c'est pour éviter qu'un service écoute déjà sur celui ci. à la bse lutim écoute sur 8080 qui a beaucoup de chance d'être déjà pris. Donc je regarde le premier port disponible après 8095
- pour les droits du service, je n'ai pas de soucis en effet, car après avoir lancé le service `service lutim start` je refait un `chown lutim:lutim /var/www/lutim -R` pour que lutim soit le propriétaire des fichiers créés par l'init (genre `lutim.db`,`tmp` je crois).
- `sudo yunohost app addaccess $app -u $admin` ajoute l'admin aux utilisateurs autorisés à accéder à l'app. C'est un peu inutile j'avoue car yunohost a pour politique d'autoriser tout le monde pour une app nouvelle (pour moi l'inverse aurait été plus judicieux).
- je m'en fou des spams, tu peux y aller, je trouve cool qu'on bosse ensemble et tant que t'as des idées c'est cool =)

**Comment by matlink** [comment]
L'installation des paquets est vraiment très très lente sur ma machine virtuelle Virtualbox. Pour la date est à l'heure, je vois pas le problème :/

**Comment by maniackcrudelis** [comment]
Brièvement (je suis sur mon téléphone)
Le problème de la date est un problème qui se pose avec les instantanés sans les additions client. 
Au démarrage d'un instantané enregistré à son état d'exécution (pas de reboot propre) la date est celle de la dernière exécution.
Il faut passer en ligne de commande sur l'hôte pour réinitialiser l'horloge du bios de la vm.

**Comment by maniackcrudelis** [comment]
- La vérif du port c'est une super idée! Je prenais arbitrairement 8095, mais chercher un port dispo c'est carrément plus intelligent.

- Pour les droits, pas de problème non plus par la suite, pour la suppression des images et tout? Si on peut éviter de patcher le script init sur ce point, c'est pas plus mal.

- ```sudo yunohost app addaccess $app -u $admin```, intéressant, je connaissait pas cette commande, je vais m'en servir je pense! Par contre là, je pense que c'est contre productif, car si tu assignes UN user, tu rejettes les autres. Et lutim ne devrait pas avoir de restrictions d'accès parmi les users du serveur je pense.

- J'ai créé un kanboard, ça devrait fonctionner. Ça a beaucoup évolué depuis que je l'ai essayé, on verra à l'usage. Par contre il y a un petit problème d'http auth sans gravité pour nous. J'ai posté une issue, on verra.

**Comment by matlink** [comment]
Non pas de problèmes de droits pour les images. 
Pour l'accès aux utilisateurs, de base yunohost accepte tous les utilisateurs du système donc ça pose pas de soucis. On peut retirer la commande je pense. 
T'as le lien du kanboard ?

Le 13 mars 2015 00:42:17 CET, Maniack Crudelis <notifications@github.com> a écrit :
>- La vérif du port c'est une super idée! Je prenais arbitrairement
>8095, mais chercher un port dispo c'est carrément plus intelligent.
>
>- Pour les droits, pas de problème non plus par la suite, pour la
>suppression des images et tout? Si on peut éviter de patcher le script
>init sur ce point, c'est pas plus mal.
>
>- ```sudo yunohost app addaccess $app -u $admin```, intéressant, je
>connaissait pas cette commande, je vais m'en servir je pense! Par
>contre là, je pense que c'est contre productif, car si tu assignes UN
>user, tu rejettes les autres. Et lutim ne devrait pas avoir de
>restrictions d'accès parmi les users du serveur je pense.
>
>- J'ai créé un kanboard, ça devrait fonctionner. Ça a beaucoup évolué
>depuis que je l'ai essayé, on verra à l'usage. Par contre il y a un
>petit problème d'http auth sans gravité pour nous. J'ai posté une
>issue, on verra.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/maniackcrudelis/lutim_ynh/issues/1#issuecomment-78697210

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by maniackcrudelis** [comment]
Je t'ai envoyé le lien sur jabber avec login et mdp à changer hier soir.
Si tu ne les retrouve pas  je te renverrai tout ça
