### ISSUE TITLE
What is the license?

### ISSUE THREAD

**Issue by RyDroid** [maniackcrudelis/lutim_ynh#12]
What is the license? Is it a free/libre one?

**Comment by maniackcrudelis** [comment]
Salut,

les packages pour Yunohost ne sont fait qu'avec des logiciels libres.
Lutim est sous license AGPL.
Cf le [site officiel](https://lut.im/), ou le [dépôt github](https://github.com/ldidry/lutim/blob/master/LICENSE).

**Comment by RyDroid** [comment]
Salut.
Les fichiers de conf et les scripts de ce dépot n'ont pas de licence (AGPL3 ou une autre licence libre), d'ou le problème. Il y a d'ailleurs une clé pour cela dans le manifest. https://yunohost.org/packaging_apps_fr

**Comment by maniackcrudelis** [comment]
Aux dernières nouvelles dont je dispose (qui ne sont pas forcément à jour), c'est un point qui n'est toujours pas défini.
Le débat tournant autour de la question de la licence à indiquer dans le manifest et dans un fichier de licence, celle de l'app ou celle du script. Si ce dernier doit en avoir une.

Afin d'uniformiser les packages, j'attends une réponse officielle de l'équipe avant de mettre à jour l'ensemble de mes packages.
En attendant, les scripts sont bien sûr librement utilisable.

**Comment by M5oul** [comment]
Il a été décidé de mettre la licence du paquet dans un fichier `LICENSE` à la racine du paquet. Dans le manifest, le champ `license` correspond à la licence du logiciel packagé.
* [Paquet d’exemple](https://github.com/YunoHost/example_ynh)
* [Packaging d’app](https://yunohost.org/#/packaging_apps_fr)

**Comment by maniackcrudelis** [comment]
J'ai commencé à mettre à jour l'ensemble de mes packages, j'ajoute également la licence.
