### ISSUE TITLE
Lutim privé et accès public sur les images

### ISSUE THREAD

**Issue by maniackcrudelis** [maniackcrudelis/lutim_ynh#2]
Pour ma part, c'est encore le point qui me pose problème. Réussir à donner un accès public uniquement sur les images.

Après moult tentatives infructueuses, je suis sur cette regex:
/[0-9A-Za-z]\{8\}
Mais je suis pas très convaincu car ça implique que les images ont 8 caractères et que cette option ne change pas.

Tu parlais de ```skipped_urls = /lutim``` pour rendre public /lutim et ensuite rendre privé les parties qui nous intéresse.
Cette une partie qui est très mal documentée je trouve. Mais il me semble que l'url est relative au path de l'app. Donc ```/``` seul devrait pointer sur domain.tld/lutim/ et ```/lutim``` sur domain.tld/lutim/lutim
Mais je n'ai pas tenté. Tu as eu de bon résultats?

**Comment by matlink** [comment]
C'est ça.
As-tu vu comment j'ai fait pour accepter les images en mode publique sans donner les accès à l'upload ? C'est les regex que nous  a filé le dev de lutim. Ca fonctionne nickel, sauf que c'est ACCEPT par défaut et REJECT pour certains path, le contraire en fait.
En quoi est-ce gênant ?

**Comment by maniackcrudelis** [comment]
Je n'ai pas essayé en mettant /lutim en skipped_urls en fait.
Tu pourrais posté le settings.yml, qu'on voit exactement ce que ça donne.

**Comment by matlink** [comment]
lutim # cat settings.yml 
admin: matlink
allowed_users: matlink
domain: pic.matlink.fr
final_path: /var/www/lutim
id: lutim
install_time: 1425936061
is_public: 'No'
label: Lutim
mode: private
path: /
skipped_uris: /

**Comment by maniackcrudelis** [comment]
Mais là c'est privé et tu as ```skipped_uris: /```
Donc ton instance lutim est publique là, non ?

Je remarque par contre que tu es en sous domaine, alors que je teste en sous dossier.
Ça fait peut-être une différence.

**Comment by matlink** [comment]
Oui, mon instance est publique selon yunohost mais je la rends privée en bloquant les accès vers les chemins qui permettent autre chose que le visonnage d'images : 

    # cat conf.json.persistent 
    { ...
       "protected_regex": [
	    "pic.matlink.fr/lutim/stats$",
        "pic.matlink.fr/manifest.webapp$",
        "pic.matlink.fr/$",
        "pic.matlink.fr$",
        "pic.matlink.fr/d/.*$",
        "pic.matlink.fr/m/.*$"
    ], 
    ...}

Je veux bien que tu renvoi le kanboard, car mon instance de metronome n'avait pas le module offline d'activé :/

**Comment by maniackcrudelis** [comment]
Ah ok, tu passes par le persistent ! 
Bon faudra tester tout ça depuis le settings.yml

Je sais pas si c'est pareil, je crois

**Comment by maniackcrudelis** [comment]
Désolé,  mon téléphone n'a pas un très grand écran...
Donc je crois

**Comment by maniackcrudelis** [comment]
... 
Ce bouton est joueur...

Je pense que c'est relatif depuis le settings.yml, et non absolu. 
Mais je suis sûr de rien.

**Comment by matlink** [comment]
Oui c'est relatif, faut que je teste dans un sous-dossier.
Merci pour avoir pourri ma boite mail par la même occasion xD

**Comment by maniackcrudelis** [comment]
C'était un plaisir :D

**Comment by matlink** [comment]
J'ai installé une VM avec lxc, c'est beaucoup plus efficace que du virtual box !

**Comment by maniackcrudelis** [comment]
J'ai jamais essayé, mais après lecture d'un article, au premier coup d'oeil, je dirais que j'apprécie la simplicité d'une virtual box que je peux sauvegarder, martyriser et restaurer.
Et étrangement, je n'ai pas ces problèmes de lenteur. Pourtant ma machine est moins puissante.
