### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by bacardi55** [maniackcrudelis/lutim_ynh#3]
Hi,

I tried to install lutim on my yunohost instance today.
Despite the success message in the end, accessing to the app displayed a "bad gateway error" from nginx. 

After checking the logs from the installation, I found this:

Installation du module perl carton. Attention, étape très longue...
+ sudo tee /var/log/lutim/setup_carton.log
+ sudo cpan Carton
+ yes
yes: standard output: Broken pipe
yes: write error

**Comment by maniackcrudelis** [comment]
Comme je sais que tu es francophone et que je suis un naze en anglais, je vais en profiter ;)

L'erreur de Yes n'en est pas vraiment une. Nous n'avons toutefois pas réussi à nous en débarrasser...
Il faut regarder les logs de lutim dans /var/log/lutim/, tout d'abord le log setup_carton.log et ensuite le log pruduction.log

C'est sans doute le service lutim qui n'a pas démarré pour une raison à éclaircir par ce biais.
