### ISSUE TITLE
Consultation des images privée

### ISSUE THREAD

**Issue by matlink** [maniackcrudelis/lutim_ynh#4]
Devrait-on demander à l'installation si la consultation des images doit être publique ou pas ? Car actuellement, si l'application est privée, l'accès aux images est public.

**Comment by maniackcrudelis** [comment]
Comme discuter ensemble. Le cas d'usage ne parait pas évident à première vue.
Pour ne pas alourdir le manifest, gardons cette possibilité de côté au cas où elle serait demandé par un utilisateur.
