### ISSUE TITLE
cron post-uninstall

### ISSUE THREAD

**Issue by adrien80080** [maniackcrudelis/lutim_ynh#7]
Hello,
i have installed Lutim, but, due to an error 404 when i try to use, i have deleted this app.
After the uninstall process, the cron task continue to send me many emails.

They cron files does not deleted by the uninstall script.

For the error 404, i going to open another issue.

**Comment by maniackcrudelis** [comment]
Hello,

no error is displayed when uninstalling?
cron should be deleted by the script.
https://github.com/maniackcrudelis/lutim_ynh/blob/master/scripts/remove#L21

**Comment by adrien80080** [comment]
Comme je sais que tu est francophone et que je suis nul (moi aussi ^^) en anglais, je vais en profiter 

Non, aucune erreur après la désinstallation.
Merci pour le script

**Comment by maniackcrudelis** [comment]
Oh merci !!!
J'avais vu aussi que tu étais francophone ;)

OK, je vais faire un essai de mon côté (d'autant que ma machine virtuelle à aussi un cron de lutim qui traîne dans son cron.d)

**Comment by maniackcrudelis** [comment]
Après essai d'installation et désinstallation. Le cron de lutim est supprimé sans problème.
Je clos pour le moment, ça pourra être réouvert en cas de récidive.
