### ISSUE TITLE
Error 404 after installation

### ISSUE THREAD

**Issue by adrien80080** [maniackcrudelis/lutim_ynh#8]
Hello,
when i install Lutim (domain.tld/folder ; sub.domain.tld ; domain.tld ; sub.domain.tld/folder)
i have an error 404

i use YNH with RPi2

**Comment by maniackcrudelis** [comment]
Can you check the install log?

**Comment by adrien80080** [comment]
Je réinstalle et je tente de regarder les logs ;)
Je les trouve où ?

**Comment by maniackcrudelis** [comment]
Malheureusement pour le moment, tu ne peux les voir qu'à la fin de l'installation. Yunohost ne stocke pas pour le moment les logs d'installation.

**Comment by adrien80080** [comment]
j'installe et je poste le log ici ;)

**Comment by adrien80080** [comment]
bon, je comprends pas tout, car là ca fonctionne correctement.
Ca fait une bonne semaine que je galère avec ^^

**Comment by maniackcrudelis** [comment]
Certainement que la création crains son maître. Donc le script ne veux pas échouer devant moi.
Tu peux tout de même me montrer le log, peut-être que je verrais un petit détail, sait-on jamais.

**Comment by adrien80080** [comment]
Setup_carton : https://abhd.tk/zerobin/?0130aaa2e1622e25#bJ2/uwIOFTTiN0t1j3KMg2B+pkCy5dA97ZUJof8Hvw0=

Production : https://abhd.tk/zerobin/?095b8154a3cfa687#5P93GHBGRt57D1RTVdJC/pE4i7HPWY8pMQfqhE8U+Po=

**Comment by maniackcrudelis** [comment]
Je pensais au log de l'install de l'app, pas à ces logs, qui eux, reste après l'installation.
Je pensais donc au log que tu obtiens à la fin de l'install sur la page d'admin de yunohost.

**Comment by adrien80080** [comment]
je n'ai pas eu le temps de cliquer sur "Journal", c'est directement retourné sur la liste de mes applications.

**Comment by maniackcrudelis** [comment]
Dommage, sur ces logs tout va bien, je ne décèle rien.
Mais peut-être que ta première installation avait échoué sur le setup de carton. Je vais ajouter un update avant l'apt-get install. Ça évitera peut-être un échec d'installation de paquet.

Le principal, c'est qu'à présent ça fonctionne

**Comment by adrien80080** [comment]
Encore merci pour ton aide :)
